Repository bentoml/BentoML, pull requests merged in 2020-12, with the labels that each got.

#1273 [New Feature] Add authentication token at grpc requests
  bentoml/configuration/default_bentoml.cfg
  bentoml/yatai/client/interceptor/__init__.py
  bentoml/yatai/client/interceptor/generic_client_interceptor.py
  bentoml/yatai/client/interceptor/header_client_interceptor.py
  bentoml/yatai/yatai_service.py
Labels: new feature

#1315 [Enhancement] add bentom_service.start_dev_server
  bentoml/service/__init__.py
Labels: enhancement

#1351 Fix YataiService's trailing slash bug
  bentoml/yatai/yatai_service.py
Labels: bug
