Repository bentoml/BentoML, pull requests merged in 2022-06, with the labels that each got.

#2547 fix: path for custom dockerfile templates
  bentoml/_internal/bento/build_config.py
  bentoml/_internal/bento/docker.py
  bentoml/_internal/bento/docker/entrypoint.sh
  bentoml/_internal/bento/docker/templates/base.j2
  bentoml/_internal/bento/docker/templates/miniconda_alpine.j2
  bentoml/_internal/bento/docker/templates/miniconda_debian.j2
  bentoml/_internal/bento/gen.py
  setup.cfg
Labels: ready-to-merge

#2576 chore(runner): add shcedule shortcuts to runners
  bentoml/_internal/runner/runner.py
  bentoml/_internal/server/__init__.py
  bentoml/_internal/server/runner_app.py
  tests/integration/frameworks/test_pytorch_impl.py
  tests/integration/frameworks/test_sklearn_impl.py
  tests/integration/frameworks/test_torchscript_impl.py
Labels: p1

#2579 fix(cli): cli encoding error on Windows
  bentoml/_internal/cli/__init__.py
Labels: p0

#2548 feat: dockerfile templates advanced guides
  codecov.yml
  docs/source/concepts/bento.rst
  docs/source/conf.py
  docs/source/guides/dockerfile_generation.rst
  docs/source/guides/index.rst
Labels: p1

#2634 feat: add generic protobuf
  protos/io_descriptors.proto
Labels: ready-to-merge
